### ISSUE TITLE
materials for git in RStudio - Module 2 Demo

### ISSUE THREAD

**Issue by kcranston** [Reproducible-Science-Curriculum/rr-version-control#7] opened 2015-09-26 14:46 UTC
When teaching git using GitHub only (see issue #4), the participants were eager to know how to use git on their own machines. I wonder about having some materials for git in RSTudio? There are already some nice resources online that we could re-purpose:

* [Using git with RStudio](https://jennybc.github.io/2014-05-12-ubc/ubc-r/session03_git.html) from @jennybc
* [git/GitHub with RStudio](http://kbroman.org/github_tutorial/pages/rstudio.html) from @kbroman
* [Using GitHub with R and RStudio](http://www.molecularecologist.com/2013/11/using-github-with-r-and-rstudio/) from the molecular ecologist blog

Of course, this means doing some amount of local setup (and can this be done without touching bash?). Or, just having this as a demo.

**Comment by jennybc** [comment] 2015-09-26 15:17
I just cleaned up our entire set of tutorials on this. Feel free to reuse, modify, whatever:

http://stat545-ubc.github.io/git00_index.html

**Comment by hlapp** [comment] 2015-09-26 21:16
This seems like a great idea to me that's worth trying. :+1:

**Comment by jennybc** [comment] 2015-09-26 21:21
How soon would anyone teach this? Because I have thoughts on how to eliminate/delay the need to go to the shell for beginners, i.e. accomplish the git "on ramp" from within R (other than installation).

**Comment by iamciera** [comment] 2015-09-26 21:54
I like this idea too! Especially if they are using it already throughout the course and @jennybc has already done a lot of the heavy lifting.

I never use git through RStudio, but I remember discussing this option with @fmichonneau and he was telling me that there is one git feature that RStudio doesn't support which he thought was a big caveat.  @fmichonneau, do you remember that conversation?

**Comment by jennybc** [comment] 2015-09-26 22:08
I'm guessing ithe missing feature is adding a remote and making it "upstream" of local master branch. This is part of what I'm proposing to wrap in something novice-friendly so we can work with Git and GitHub from RStudio in settings where we'd like to avoid going to the shell for magical Git incantations.

**Comment by fmichonneau** [comment] 2015-09-27 23:26
@jennybc is correct. Working with branches and doing pull request require to use the command line. However, teaching simply how to pull/push to a repository would work well and is probably enough for the purpose of the RSC.

Another challenge when I taught it in my course was that at least one student had one of the Mac OSX versions released in the past 5 years, and each of them required different tricks to get the full setup to work. Between the wiki for Software carpentry (https://github.com/swcarpentry/workshop-template/wiki/Configuration-Problems-and-Solutions), and @jennybc and @kbroman websites, none of them are insurmountable.

**Comment by iamciera** [comment] 2015-12-09 19:31
According to the new outline: https://github.com/Reproducible-Science-Curriculum/rr-version-control/wiki, create a file that outlines a demo that illustrates how to use git in Rstudio.

**Closed** 2015-12-10 15:56 UTC
